# render.yaml
services:
  - type: web
    name: sales-dashboard-backend
    env: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-uri
          property: connectionString